Repository MAXOUXAX/Isabelle, pull requests merged in 2024-12, with the labels that each got.

#8 fix: Slash Commands deployment
  package-lock.json
  package.json
  src/index.ts
  src/manager/commands/command.interface.ts
  src/manager/commands/command.manager.ts
  src/modules/hot-potato/commands/hot-potato.command.ts
Labels: bug, in review

#20 chore: group dependabot updates
  .github/dependabot.yml
Labels: dependencies, approved

#32 ci: improved build and deploy workflows
  .github/workflows/build.yml
  .github/workflows/deployment.yml
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#15 ci: add eslint github workflow
  .github/workflows/eslint.yml
Labels: in review

#3 Module Coiffeur
  src/index.ts
  src/modules/coiffeur/coiffeur.constants.ts
  src/modules/coiffeur/coiffeur.module.ts
  src/modules/coiffeur/events/coiffeur-message.listener.ts
  src/utils/dictionnary.ts
Labels: enhancement, in review
