Repository MAXOUXAX/Isabelle, pull requests merged in 2025-09, with the labels that each got.

#65 Add gitattributes to autoconvert eof to LF
  .gitattributes
Labels: technique

#72 feat(sutom): render the game's board using an image
  package-lock.json
  package.json
  public/resources/sutom/Outfit-Bold.ttf
  src/modules/sutom/canvas/canvas-utils.ts
  src/modules/sutom/canvas/sutom-board-image.ts
  src/modules/sutom/canvas/sutom-theme.ts
  src/modules/sutom/commands/subcommands/start-sutom.ts
  src/modules/sutom/commands/subcommands/stop-sutom.ts
  src/modules/sutom/commands/subcommands/sutom-guess.ts
  src/modules/sutom/core/sutom-game.ts
Labels: enhancement

#58 Schedule Commands
  .env.example
  .github/ISSUE_TEMPLATE/rapport-de-bug.md
  .github/ISSUE_TEMPLATE/suggérer-une-idée-pour-isabelle.md
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/deployment.yml
  .github/workflows/eslint.yml
  .gitignore
  .husky/pre-commit
  .prettierrc
  .vscode/settings.json
  LICENSE
  eslint.config.js
  package-lock.json
  package.json
  src/config.ts
  src/index.ts
  src/manager/commands/command.interface.ts
  src/manager/commands/command.manager.ts
  src/manager/config.manager.ts
  src/manager/interaction.manager.ts
  src/manager/modals/modal.base.ts
  src/manager/modals/modal.manager.ts
  src/modules/bot-module.ts
  src/modules/coiffeur/coiffeur.constants.ts
  src/modules/coiffeur/coiffeur.module.ts
  src/modules/coiffeur/events/coiffeur-message.listener.ts
  src/modules/core/commands/bonjour.ts
  src/modules/core/commands/ping.ts
  src/modules/core/core.module.ts
  src/modules/hot-potato/commands/hot-potato.command.ts
  src/modules/hot-potato/events/hot-potato-role.listener.ts
  src/modules/hot-potato/hot-potato.module.ts
  src/modules/planifier/commands/planifier.command.ts
  src/modules/planifier/interactions/planifier-modal-submit.interaction.ts
  src/modules/planifier/planifier.module.ts
  src/modules/schedule/commands/schedule.command.ts
  src/modules/schedule/schedule.module.ts
  src/utils/cache.ts
  src/utils/date.ts
  src/utils/dictionnary.ts
  src/utils/mention.ts
  src/utils/schedule.ts
  tsconfig.json
  tsup.config.ts
Labels: enhancement

#76 chore: improve .env.example with documentation, and add some ignored files in .gitignore
  .env.example
  .gitignore
Labels: documentation

#77 feat: add drizzle
  .env.example
  drizzle.config.ts
  drizzle/0000_faithful_night_thrasher.sql
  drizzle/0001_seed-automatic-responses.sql
  drizzle/meta/0000_snapshot.json
  drizzle/meta/0001_snapshot.json
  drizzle/meta/_journal.json
  eslint.config.js
  package-lock.json
  package.json
  src/db/index.ts
  src/db/schema.ts
  src/index.ts
  src/manager/config.manager.ts
  src/modules/automatic-responses/automatic-responses.module.ts
  src/modules/automatic-responses/events/automatic-responses.listener.ts
  src/modules/coiffeur/coiffeur.constants.ts
  src/modules/coiffeur/coiffeur.module.ts
  src/modules/coiffeur/events/coiffeur-message.listener.ts
  src/utils/cache.ts
Labels: enhancement

#83 feat(ci): add semantic release configuration and release workflow
  .github/workflows/release.yml
  .releaserc.json
  package-lock.json
  package.json
Labels: enhancement

#95 chore(copilot): introduce instructions about semantic commits
  .github/copilot-instructions.md
Labels: technique
